# Generated by Django 4.2.1 on 2023-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='blog_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(default=' ', max_length=50)),
                ('name_bank_card', models.CharField(default=' ', max_length=50)),
                ('privar_one', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_kind_of_pet', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Yoang Cat', 'Yoang Cat'), ('Kitten', 'Kitten')], default='Cat', max_length=100)),
                ('photo', models.ImageField(upload_to='cat_photos/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='men', max_length=20)),
                ('sick', models.CharField(default='men', max_length=100)),
                ('character', models.CharField(default='не визначено', max_length=100)),
                ('friendliness', models.CharField(default='не визначено', max_length=100)),
                ('features', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('breed', models.CharField(default='Без породи', max_length=50)),
                ('sterilization', models.CharField(default='Не стерилізовані', max_length=50)),
                ('vaccination', models.CharField(default='Не вакциновані', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=500)),
                ('phone_number', models.CharField(default=' ', max_length=10)),
                ('social_media_account', models.CharField(default=' ', max_length=500)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('housing_type', models.CharField(default=' ', max_length=500)),
                ('living_arrangement', models.CharField(default=' ', max_length=500)),
                ('rental_status', models.CharField(default=' ', max_length=500)),
                ('desired_pet_age', models.CharField(default=' ', max_length=500)),
                ('pet_care_experience', models.CharField(default=' ', max_length=500)),
                ('previous_pet_experience', models.CharField(default=' ', max_length=500)),
                ('your_experienc_keeping_animals', models.CharField(default=' ', max_length=500)),
                ('how_old_was_your_last_pet', models.CharField(default=' ', max_length=500)),
                ('current_pets', models.CharField(default=' ', max_length=500)),
                ('feeding_knowledge', models.CharField(default=' ', max_length=500)),
                ('neutering_spaying_attitude', models.CharField(default=' ', max_length=500)),
                ('vaccination_attitude', models.CharField(default=' ', max_length=500)),
                ('outdoor_cat_attitude', models.CharField(default=' ', max_length=500)),
                ('rules_for_keeping_dog_cat', models.CharField(default=' ', max_length=500)),
                ('dog_house_knowledge', models.CharField(default=' ', max_length=500)),
                ('decide_to_adopta_cat_dog', models.CharField(default=' ', max_length=500)),
                ('dog_training_goals', models.CharField(default=' ', max_length=500)),
                ('daily_time_commitment', models.CharField(default=' ', max_length=500)),
                ('emergency_contact', models.CharField(default=' ', max_length=500)),
                ('animal_with_health_roblems', models.CharField(default=' ', max_length=500)),
                ('ready_for_additional_expenses', models.CharField(default=' ', max_length=500)),
                ('animal_problematic_personality', models.CharField(default=' ', max_length=500)),
                ('consultations_behavioral_specialists', models.CharField(default=' ', max_length=500)),
                ('animal_may_scratch_bite_whine', models.CharField(default=' ', max_length=500)),
                ('children_in_home', models.CharField(default=' ', max_length=500)),
                ('children_lived_animals', models.CharField(default=' ', max_length=500)),
                ('everyone_ready_for', models.CharField(default=' ', max_length=500)),
                ('home_floor', models.CharField(default=' ', max_length=500)),
                ('Im_ready_for_puddles_and_piles_at_home', models.CharField(default=' ', max_length=500)),
                ('prepared_fact_animal_can_spoil_your_roperty', models.CharField(default=' ', max_length=500)),
                ('how_do_you_see_your_animal', models.CharField(default=' ', max_length=500)),
                ('travel_plans', models.CharField(default=' ', max_length=500)),
                ('how_do_you_give_up_an_animal', models.CharField(default=' ', max_length=500)),
                ('ready_to_provide_photo_video_of_apartment', models.CharField(default=' ', max_length=500)),
                ('signing_an_official_contract_passport', models.CharField(default=' ', max_length=500)),
                ('photo_video_reports_of_your_pet', models.CharField(default=' ', max_length=500)),
                ('how_did_you_find_out_about_our_shelter', models.CharField(default=' ', max_length=500)),
                ('application_approved', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats', models.IntegerField()),
                ('dogs', models.IntegerField()),
                ('food', models.IntegerField()),
                ('found_family', models.IntegerField()),
                ('debt', models.IntegerField(default=0)),
            ],
        ),
    ]
