# Generated by Django 4.2.1 on 2023-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='tactility',
            field=models.CharField(default='не визначено', max_length=100),
        ),
    ]
