# Generated by Django 4.2.1 on 2023-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_cat_peculiarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='sick',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
