# Generated by Django 4.2.1 on 2023-07-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_alter_cat_sick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='breed',
        ),
    ]
