# Generated by Django 4.2.1 on 2023-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_remove_cat_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cat_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='photo',
        ),
        migrations.AddField(
            model_name='cat',
            name='images',
            field=models.ManyToManyField(related_name='cats', to='cat.image'),
        ),
    ]
