# Generated by Django 4.2.1 on 2023-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_image_remove_cat_photo_cat_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='images',
        ),
        migrations.AddField(
            model_name='cat',
            name='photo_1',
            field=models.ImageField(default='_', upload_to='cat_photos/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='photo_2',
            field=models.ImageField(default='_', upload_to='cat_photos/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='photo_3',
            field=models.ImageField(default='_', upload_to='cat_photos/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='video_link',
            field=models.URLField(default='_'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
