# Generated by Django 4.2.1 on 2023-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_remove_cat_images_cat_photo_1_cat_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo_1',
            field=models.ImageField(default='', upload_to='cat_photos/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo_2',
            field=models.ImageField(default='', upload_to='cat_photos/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo_3',
            field=models.ImageField(default='', upload_to='cat_photos/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='video_link',
            field=models.URLField(default=''),
        ),
    ]
