# Generated by Django 4.2.1 on 2023-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_alter_cat_photo_1_alter_cat_photo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ournumbers',
            name='found_family',
        ),
    ]
