# Generated by Django 4.2.1 on 2023-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_remove_ournumbers_found_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
